description: Quotas update for vEPG VNF 
heat_template_version: 'queens'

parameters:
  project:
    type: string
    description: "Name of the project to bump quotas"
    default: "admin"
  max_file_size:
    type: number 
    description: "Max Personality file size"
    default: 8388608

resources:
  quota:
    type: OS::Nova::Quota
    properties:
      cores: -1
      instances: -1
      key_pairs: -1
      metadata_items: -1
      project: { get_param: project }
      ram: -1
      server_group_members: -1
      server_groups: -1
